apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crb
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
spec:
  serviceAccount: {{ .Release.Name }}-sa
  containers:
  - name: kube-ez
    image: kitarp29/k8s-api:latest
    ports:
    - containerPort: 8000
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 300
      successThreshold: 1
      failureThreshold: 3
      httpGet:
        path: /
        port: 8000
