apiVersion: v1
kind: Pod
metadata:
  name: kube-ez
spec:
  serviceAccount: kube-ez
  containers:
  - name: kube-ez
    image: kitarp29/k8s-api:10
    ports:
    - containerPort: 8000
    securityContext:
      allowPrivilegeEscalation: false