name: Go mod tidy
on:
  push:
  pull_request:

jobs:
  build-modules:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: tidy
        uses: paulvollmer/action-golang-gosum@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: go mod tidy
