name: Kube-ez CI
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: kube-ez
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
         
  Test-on-cluster:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - run: |
          kubectl cluster-info
          kubectl get nodes

      - name : Preparing cluster for kube-ez
      # I know this is Wierd that it works, but running the forward command twice does work!
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kitarp29/kube-ez/main/yamls/sa.yaml
          kubectl apply -f https://raw.githubusercontent.com/kitarp29/kube-ez/main/yamls/crb.yaml
          kubectl run kube-ez --image=ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} --port=8000
          sleep 20
          kubectl get po
          kubectl port-forward kube-ez 8000:8000 &>/dev/null &
          sleep 5
          kubectl port-forward kube-ez 8000:8000 &>/dev/null &
      - run: |
          curl -i http://localhost:8000/